I will always be walking in your shadows...

What's the point of working hard then? If everyone will always look at you...

Heh... Do people really care about me? Or am I just a tool for them...

It hurts...

Even though this feeling has faded... I still feel the thought echoing inside my heart...

